set(_AMENT_PACKAGE_NAME "rt2_assignment1_ros2")
set(rt2_assignment1_ros2_VERSION "0.0.0")
set(rt2_assignment1_ros2_MAINTAINER "root <root@todo.todo>")
set(rt2_assignment1_ros2_BUILD_DEPENDS "rclcpp" "std_msgs" "rosidl_default_generators")
set(rt2_assignment1_ros2_BUILDTOOL_DEPENDS "ament_cmake")
set(rt2_assignment1_ros2_BUILD_EXPORT_DEPENDS )
set(rt2_assignment1_ros2_BUILDTOOL_EXPORT_DEPENDS )
set(rt2_assignment1_ros2_EXEC_DEPENDS "rclcpp" "std_msgs" "rosidl_default_runtime")
set(rt2_assignment1_ros2_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(rt2_assignment1_ros2_GROUP_DEPENDS )
set(rt2_assignment1_ros2_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(rt2_assignment1_ros2_DEPRECATED "")
set(rt2_assignment1_ros2_EXPORT_TAGS)
list(APPEND rt2_assignment1_ros2_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
list(APPEND rt2_assignment1_ros2_EXPORT_TAGS "<ros1_bridge mapping_rules=\"mapping_rule.yaml\"/>")
