# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# compile CXX with /usr/bin/c++
CXX_FLAGS = -fPIC   -Wall -Wextra -Wpedantic -std=gnu++14

CXX_DEFINES = -DDEFAULT_RMW_IMPLEMENTATION=rmw_fastrtps_cpp -DRCUTILS_ENABLE_FAULT_INJECTION -DROS_PACKAGE_NAME=\"rt2_assignment1_ros2\" -DSPDLOG_COMPILED_LIB -Dposition_server_EXPORTS

CXX_INCLUDES = -I/root/ros2/build/rt2_assignment1_ros2/rosidl_generator_cpp -isystem /opt/ros/foxy/include 

